FROM ghcr.io/xpans-audio/linux-build-environments-aarch64:latest
RUN apt-get update; apt-get install --assume-yes \
    libx11-dev:arm64 \
    libx11-xcb-dev:arm64 \
    libgl1-mesa-dev:arm64 \
    libxcb1-dev:arm64 \
    libxcb-dri2-0-dev:arm64 \
    libxcb-icccm4-dev:arm64 \
    libxcursor-dev:arm64 \
    libwayland-dev:arm64 \
